import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './theme-config.css';
import "./globals.css";
import NavBar from "./NavBar";
import '@radix-ui/themes/styles.css';
import { Theme} from '@radix-ui/themes';

const inter = Inter({ 
  subsets: ["latin"],
  variable: '--font-inter',

});

export const metadata: Metadata = {
  title: "Create Ayus App",
  description: "Generated by Ayu app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
      <Theme accentColor="green">
        <NavBar/>
        <main className="p-6">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
